---
deployment:
      tasks:
        - export DEPLOYPATH=/home/douglasc/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp -R css $DEPLOYPATH
        - /bin/cp -R fonts $DEPLOYPATH
        - /bin/cp -R js $DEPLOYPATH